### ISSUE TITLE
2. Add Todo

### ISSUE THREAD

**Issue by Eltayeb-Elgaali** [yildiraykoyuncu/encapsulation-list-prototype-group-5#3]
## 2. User Story: Add Todo

__As a user I want to be able to add new Todo__

- _Given I have initial page open I should be able to type into the input field and add a new todo to the list below input field by hitting enter_

### REPO

- [x] This user story is developed on branch `2-add-todo`.
- [x] This branch is merged to `master` branch after completion.

#### DATA

- [x] Add a `addTodo` method to TodoList class.

#### HANDLER

- [x] Add addTodoHandler.
