### ISSUE TITLE
4. Delete Todo

### ISSUE THREAD

**Issue by Eltayeb-Elgaali** [yildiraykoyuncu/encapsulation-list-prototype-group-5#5]
## 4. User Story: Delete Todo

__As a user I would like to be able to delete todos__

- _Given I have the app open I should see a delete button beside every todo which deletes the corresponding todo upon click_

### REPO

- [x] This user story is developed on branch `4-delete-todo`.
- [x] This branch is merged to `master` branch after completion.

#### DATA

- [x] Add a `deleteTodo` method to the TodoList class which deletes the corresponding todo object from the todolist.

#### HANDLER

- [x] Add a `deleteTodoHandler` method to the TodoList class.

#### LISTENER
